[package]
name = "mc-snos"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
# Substrate
sc-client-api = { workspace = true }
sp-api = { workspace = true, features = ["std"] }
sp-blockchain = { workspace = true }
sp-runtime = { workspace = true, features = ["std"] }
sp-storage = { workspace = true, features = ["std"] }
starknet_api = { workspace = true, features = ["std"] }

# Madara
mp-digest-log = { workspace = true, features = ["std"] }
mp-storage = { workspace = true, features = ["std"] }
pallet-starknet = { workspace = true }

# Starknet
blockifier = { workspace = true, features = ["std"] }
snos = { git = "https://github.com/keep-starknet-strange/snos", branch = "main" }

futures = "0.3.21"
indexmap = { workspace = true }
log = { workspace = true }
