---
- name: "breaking-change"
  color: ee0701
  description:
    "A change that changes the API or breaks backward compatibility for users."
- name: "bugfix"
  color: ee0701
  description:
    "Inconsistencies or issues which will cause a problem for users or
    implementors."
- name: "documentation"
  color: 0052cc
  description: "Solely about the documentation of the project."
- name: "enhancement"
  color: 1d76db
  description: "Enhancement of the code, not introducing new features."
- name: "refactor"
  color: 1d76db
  description:
    "Updating the code with simpler, easier to understand or more efficient
    syntax or methods, but not introducing new features."
- name: "performance"
  color: 1d76db
  description:
    "Improving performance of the project, not introducing new features."
- name: "new-feature"
  color: 0e8a16
  description: "New features or options."
- name: "maintenance"
  color: 2af79e
  description: "Generic maintenance tasks."
- name: "ci"
  color: 1d76db
  description: "Work that improves the continuous integration."
- name: "dependencies"
  color: 1d76db
  description: "Change in project dependencies."

- name: "in-progress"
  color: fbca04
  description: "Issue is currently being worked on by a developer."
- name: "stale"
  color: fef2c0
  description: "No activity for quite some time."
- name: "no-stale"
  color: fef2c0
  description: "This is exempt from the stale bot."

- name: "security"
  color: ee0701
  description: "Addressing a vulnerability or security risk in this project."
- name: "incomplete"
  color: fef2c0
  description: "Missing information."
- name: "invalid"
  color: fef2c0
  description:
    "This is off-topic, spam, or otherwise doesn't apply to this project."

- name: "beginner-friendly"
  color: 0e8a16
  description:
    "Good first issue for people wanting to contribute to this project."
- name: "help-wanted"
  color: 0e8a16
  description:
    "We need some extra helping hands or expertise in order to resolve this!"

- name: "priority-critical"
  color: ee0701
  description: "Must be addressed as soon as possible."
- name: "priority-high"
  color: b60205
  description:
    "After critical issues are fixed, these should be dealt with before any
    further issues."
- name: "priority-medium"
  color: 0e8a16
  description: "This issue may be useful, and needs some attention."
- name: "priority-low"
  color: e4ea8a
  description: "Nice addition, maybe... someday..."

- name: "major"
  color: b60205
  description: "This PR causes a major bump in the version number."
- name: "minor"
  color: 0e8a16
  description: "This PR causes a minor bump in the version number."
