// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/generativelabs/btcserver/internal/db/ent/predicate"
	"github.com/generativelabs/btcserver/internal/db/ent/stake"
)

// StakeUpdate is the builder for updating Stake entities.
type StakeUpdate struct {
	config
	hooks    []Hook
	mutation *StakeMutation
}

// Where appends a list predicates to the StakeUpdate builder.
func (su *StakeUpdate) Where(ps ...predicate.Stake) *StakeUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetStaker sets the "staker" field.
func (su *StakeUpdate) SetStaker(s string) *StakeUpdate {
	su.mutation.SetStaker(s)
	return su
}

// SetNillableStaker sets the "staker" field if the given value is not nil.
func (su *StakeUpdate) SetNillableStaker(s *string) *StakeUpdate {
	if s != nil {
		su.SetStaker(*s)
	}
	return su
}

// SetTx sets the "tx" field.
func (su *StakeUpdate) SetTx(s string) *StakeUpdate {
	su.mutation.SetTx(s)
	return su
}

// SetNillableTx sets the "tx" field if the given value is not nil.
func (su *StakeUpdate) SetNillableTx(s *string) *StakeUpdate {
	if s != nil {
		su.SetTx(*s)
	}
	return su
}

// SetStart sets the "start" field.
func (su *StakeUpdate) SetStart(i int64) *StakeUpdate {
	su.mutation.ResetStart()
	su.mutation.SetStart(i)
	return su
}

// SetNillableStart sets the "start" field if the given value is not nil.
func (su *StakeUpdate) SetNillableStart(i *int64) *StakeUpdate {
	if i != nil {
		su.SetStart(*i)
	}
	return su
}

// AddStart adds i to the "start" field.
func (su *StakeUpdate) AddStart(i int64) *StakeUpdate {
	su.mutation.AddStart(i)
	return su
}

// SetDuration sets the "duration" field.
func (su *StakeUpdate) SetDuration(i int64) *StakeUpdate {
	su.mutation.ResetDuration()
	su.mutation.SetDuration(i)
	return su
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (su *StakeUpdate) SetNillableDuration(i *int64) *StakeUpdate {
	if i != nil {
		su.SetDuration(*i)
	}
	return su
}

// AddDuration adds i to the "duration" field.
func (su *StakeUpdate) AddDuration(i int64) *StakeUpdate {
	su.mutation.AddDuration(i)
	return su
}

// SetAmount sets the "amount" field.
func (su *StakeUpdate) SetAmount(i int64) *StakeUpdate {
	su.mutation.ResetAmount()
	su.mutation.SetAmount(i)
	return su
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (su *StakeUpdate) SetNillableAmount(i *int64) *StakeUpdate {
	if i != nil {
		su.SetAmount(*i)
	}
	return su
}

// AddAmount adds i to the "amount" field.
func (su *StakeUpdate) AddAmount(i int64) *StakeUpdate {
	su.mutation.AddAmount(i)
	return su
}

// SetRewardReceiver sets the "reward_receiver" field.
func (su *StakeUpdate) SetRewardReceiver(s string) *StakeUpdate {
	su.mutation.SetRewardReceiver(s)
	return su
}

// SetNillableRewardReceiver sets the "reward_receiver" field if the given value is not nil.
func (su *StakeUpdate) SetNillableRewardReceiver(s *string) *StakeUpdate {
	if s != nil {
		su.SetRewardReceiver(*s)
	}
	return su
}

// SetEnd sets the "end" field.
func (su *StakeUpdate) SetEnd(b bool) *StakeUpdate {
	su.mutation.SetEnd(b)
	return su
}

// SetNillableEnd sets the "end" field if the given value is not nil.
func (su *StakeUpdate) SetNillableEnd(b *bool) *StakeUpdate {
	if b != nil {
		su.SetEnd(*b)
	}
	return su
}

// Mutation returns the StakeMutation object of the builder.
func (su *StakeUpdate) Mutation() *StakeMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *StakeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *StakeUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *StakeUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *StakeUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *StakeUpdate) check() error {
	if v, ok := su.mutation.Staker(); ok {
		if err := stake.StakerValidator(v); err != nil {
			return &ValidationError{Name: "staker", err: fmt.Errorf(`ent: validator failed for field "Stake.staker": %w`, err)}
		}
	}
	if v, ok := su.mutation.GetTx(); ok {
		if err := stake.TxValidator(v); err != nil {
			return &ValidationError{Name: "tx", err: fmt.Errorf(`ent: validator failed for field "Stake.tx": %w`, err)}
		}
	}
	if v, ok := su.mutation.RewardReceiver(); ok {
		if err := stake.RewardReceiverValidator(v); err != nil {
			return &ValidationError{Name: "reward_receiver", err: fmt.Errorf(`ent: validator failed for field "Stake.reward_receiver": %w`, err)}
		}
	}
	return nil
}

func (su *StakeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(stake.Table, stake.Columns, sqlgraph.NewFieldSpec(stake.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Staker(); ok {
		_spec.SetField(stake.FieldStaker, field.TypeString, value)
	}
	if value, ok := su.mutation.GetTx(); ok {
		_spec.SetField(stake.FieldTx, field.TypeString, value)
	}
	if value, ok := su.mutation.Start(); ok {
		_spec.SetField(stake.FieldStart, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedStart(); ok {
		_spec.AddField(stake.FieldStart, field.TypeInt64, value)
	}
	if value, ok := su.mutation.Duration(); ok {
		_spec.SetField(stake.FieldDuration, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedDuration(); ok {
		_spec.AddField(stake.FieldDuration, field.TypeInt64, value)
	}
	if value, ok := su.mutation.Amount(); ok {
		_spec.SetField(stake.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedAmount(); ok {
		_spec.AddField(stake.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := su.mutation.RewardReceiver(); ok {
		_spec.SetField(stake.FieldRewardReceiver, field.TypeString, value)
	}
	if value, ok := su.mutation.End(); ok {
		_spec.SetField(stake.FieldEnd, field.TypeBool, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stake.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// StakeUpdateOne is the builder for updating a single Stake entity.
type StakeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StakeMutation
}

// SetStaker sets the "staker" field.
func (suo *StakeUpdateOne) SetStaker(s string) *StakeUpdateOne {
	suo.mutation.SetStaker(s)
	return suo
}

// SetNillableStaker sets the "staker" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableStaker(s *string) *StakeUpdateOne {
	if s != nil {
		suo.SetStaker(*s)
	}
	return suo
}

// SetTx sets the "tx" field.
func (suo *StakeUpdateOne) SetTx(s string) *StakeUpdateOne {
	suo.mutation.SetTx(s)
	return suo
}

// SetNillableTx sets the "tx" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableTx(s *string) *StakeUpdateOne {
	if s != nil {
		suo.SetTx(*s)
	}
	return suo
}

// SetStart sets the "start" field.
func (suo *StakeUpdateOne) SetStart(i int64) *StakeUpdateOne {
	suo.mutation.ResetStart()
	suo.mutation.SetStart(i)
	return suo
}

// SetNillableStart sets the "start" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableStart(i *int64) *StakeUpdateOne {
	if i != nil {
		suo.SetStart(*i)
	}
	return suo
}

// AddStart adds i to the "start" field.
func (suo *StakeUpdateOne) AddStart(i int64) *StakeUpdateOne {
	suo.mutation.AddStart(i)
	return suo
}

// SetDuration sets the "duration" field.
func (suo *StakeUpdateOne) SetDuration(i int64) *StakeUpdateOne {
	suo.mutation.ResetDuration()
	suo.mutation.SetDuration(i)
	return suo
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableDuration(i *int64) *StakeUpdateOne {
	if i != nil {
		suo.SetDuration(*i)
	}
	return suo
}

// AddDuration adds i to the "duration" field.
func (suo *StakeUpdateOne) AddDuration(i int64) *StakeUpdateOne {
	suo.mutation.AddDuration(i)
	return suo
}

// SetAmount sets the "amount" field.
func (suo *StakeUpdateOne) SetAmount(i int64) *StakeUpdateOne {
	suo.mutation.ResetAmount()
	suo.mutation.SetAmount(i)
	return suo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableAmount(i *int64) *StakeUpdateOne {
	if i != nil {
		suo.SetAmount(*i)
	}
	return suo
}

// AddAmount adds i to the "amount" field.
func (suo *StakeUpdateOne) AddAmount(i int64) *StakeUpdateOne {
	suo.mutation.AddAmount(i)
	return suo
}

// SetRewardReceiver sets the "reward_receiver" field.
func (suo *StakeUpdateOne) SetRewardReceiver(s string) *StakeUpdateOne {
	suo.mutation.SetRewardReceiver(s)
	return suo
}

// SetNillableRewardReceiver sets the "reward_receiver" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableRewardReceiver(s *string) *StakeUpdateOne {
	if s != nil {
		suo.SetRewardReceiver(*s)
	}
	return suo
}

// SetEnd sets the "end" field.
func (suo *StakeUpdateOne) SetEnd(b bool) *StakeUpdateOne {
	suo.mutation.SetEnd(b)
	return suo
}

// SetNillableEnd sets the "end" field if the given value is not nil.
func (suo *StakeUpdateOne) SetNillableEnd(b *bool) *StakeUpdateOne {
	if b != nil {
		suo.SetEnd(*b)
	}
	return suo
}

// Mutation returns the StakeMutation object of the builder.
func (suo *StakeUpdateOne) Mutation() *StakeMutation {
	return suo.mutation
}

// Where appends a list predicates to the StakeUpdate builder.
func (suo *StakeUpdateOne) Where(ps ...predicate.Stake) *StakeUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *StakeUpdateOne) Select(field string, fields ...string) *StakeUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Stake entity.
func (suo *StakeUpdateOne) Save(ctx context.Context) (*Stake, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *StakeUpdateOne) SaveX(ctx context.Context) *Stake {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *StakeUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *StakeUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *StakeUpdateOne) check() error {
	if v, ok := suo.mutation.Staker(); ok {
		if err := stake.StakerValidator(v); err != nil {
			return &ValidationError{Name: "staker", err: fmt.Errorf(`ent: validator failed for field "Stake.staker": %w`, err)}
		}
	}
	if v, ok := suo.mutation.GetTx(); ok {
		if err := stake.TxValidator(v); err != nil {
			return &ValidationError{Name: "tx", err: fmt.Errorf(`ent: validator failed for field "Stake.tx": %w`, err)}
		}
	}
	if v, ok := suo.mutation.RewardReceiver(); ok {
		if err := stake.RewardReceiverValidator(v); err != nil {
			return &ValidationError{Name: "reward_receiver", err: fmt.Errorf(`ent: validator failed for field "Stake.reward_receiver": %w`, err)}
		}
	}
	return nil
}

func (suo *StakeUpdateOne) sqlSave(ctx context.Context) (_node *Stake, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stake.Table, stake.Columns, sqlgraph.NewFieldSpec(stake.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Stake.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stake.FieldID)
		for _, f := range fields {
			if !stake.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != stake.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Staker(); ok {
		_spec.SetField(stake.FieldStaker, field.TypeString, value)
	}
	if value, ok := suo.mutation.GetTx(); ok {
		_spec.SetField(stake.FieldTx, field.TypeString, value)
	}
	if value, ok := suo.mutation.Start(); ok {
		_spec.SetField(stake.FieldStart, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedStart(); ok {
		_spec.AddField(stake.FieldStart, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.Duration(); ok {
		_spec.SetField(stake.FieldDuration, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedDuration(); ok {
		_spec.AddField(stake.FieldDuration, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.Amount(); ok {
		_spec.SetField(stake.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedAmount(); ok {
		_spec.AddField(stake.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.RewardReceiver(); ok {
		_spec.SetField(stake.FieldRewardReceiver, field.TypeString, value)
	}
	if value, ok := suo.mutation.End(); ok {
		_spec.SetField(stake.FieldEnd, field.TypeBool, value)
	}
	_node = &Stake{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stake.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
