// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/generativelabs/btcserver/internal/db/ent/stake"
)

// Stake is the model entity for the Stake schema.
type Stake struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Staker holds the value of the "staker" field.
	Staker string `json:"staker,omitempty"`
	// Tx holds the value of the "tx" field.
	Tx string `json:"tx,omitempty"`
	// Start holds the value of the "start" field.
	Start int64 `json:"start,omitempty"`
	// Duration holds the value of the "duration" field.
	Duration int64 `json:"duration,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount int64 `json:"amount,omitempty"`
	// RewardReceiver holds the value of the "reward_receiver" field.
	RewardReceiver string `json:"reward_receiver,omitempty"`
	// End holds the value of the "end" field.
	End          bool `json:"end,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Stake) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case stake.FieldEnd:
			values[i] = new(sql.NullBool)
		case stake.FieldID, stake.FieldStart, stake.FieldDuration, stake.FieldAmount:
			values[i] = new(sql.NullInt64)
		case stake.FieldStaker, stake.FieldTx, stake.FieldRewardReceiver:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Stake fields.
func (s *Stake) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stake.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case stake.FieldStaker:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field staker", values[i])
			} else if value.Valid {
				s.Staker = value.String
			}
		case stake.FieldTx:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tx", values[i])
			} else if value.Valid {
				s.Tx = value.String
			}
		case stake.FieldStart:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field start", values[i])
			} else if value.Valid {
				s.Start = value.Int64
			}
		case stake.FieldDuration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration", values[i])
			} else if value.Valid {
				s.Duration = value.Int64
			}
		case stake.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				s.Amount = value.Int64
			}
		case stake.FieldRewardReceiver:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reward_receiver", values[i])
			} else if value.Valid {
				s.RewardReceiver = value.String
			}
		case stake.FieldEnd:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field end", values[i])
			} else if value.Valid {
				s.End = value.Bool
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Stake.
// This includes values selected through modifiers, order, etc.
func (s *Stake) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// Update returns a builder for updating this Stake.
// Note that you need to call Stake.Unwrap() before calling this method if this Stake
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Stake) Update() *StakeUpdateOne {
	return NewStakeClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Stake entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Stake) Unwrap() *Stake {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Stake is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Stake) String() string {
	var builder strings.Builder
	builder.WriteString("Stake(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("staker=")
	builder.WriteString(s.Staker)
	builder.WriteString(", ")
	builder.WriteString("tx=")
	builder.WriteString(s.Tx)
	builder.WriteString(", ")
	builder.WriteString("start=")
	builder.WriteString(fmt.Sprintf("%v", s.Start))
	builder.WriteString(", ")
	builder.WriteString("duration=")
	builder.WriteString(fmt.Sprintf("%v", s.Duration))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", s.Amount))
	builder.WriteString(", ")
	builder.WriteString("reward_receiver=")
	builder.WriteString(s.RewardReceiver)
	builder.WriteString(", ")
	builder.WriteString("end=")
	builder.WriteString(fmt.Sprintf("%v", s.End))
	builder.WriteByte(')')
	return builder.String()
}

// Stakes is a parsable slice of Stake.
type Stakes []*Stake
