[package]
name = "mp-snos-output"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Primitives for Starknet OS output"
authors = { workspace = true }
repository = { workspace = true }

[dependencies]
mp-messages = { workspace = true }
parity-scale-codec = { workspace = true, features = [
  "derive",
], optional = true }
scale-info = { workspace = true, features = ["derive"], optional = true }
starknet_api = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
assert_matches = "1.5.0"
hex = "*"

[features]
parity-scale-codec = [
  "dep:parity-scale-codec",
  "mp-messages/parity-scale-codec",
]
scale-info = ["dep:scale-info", "mp-messages/scale-info"]
