{
 "title": "Substrate Service Tasks",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodename",
    "label": "Instance filter",
    "query": "${metric_namespace}_process_start_time_seconds"
   },
   { "name": "metric_namespace", "label": "Prefix of the metrics", "query": "${VAR_METRIC_NAMESPACE}" },
   { "name": "data_source", "label": "Source of all the data", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "$nodename", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "nodename" },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU time spent on each task",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(${metric_namespace}_tasks_polling_duration_sum{instance=~\"${nodename}\"}[$__rate_interval])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Task polling rate per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(${metric_namespace}_tasks_polling_duration_count{instance=~\"${nodename}\"}[$__rate_interval])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Average time it takes to call Future::poll()",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(${metric_namespace}_tasks_polling_duration_sum{instance=~\"${nodename}\"}[$__rate_interval]) / increase(${metric_namespace}_tasks_polling_duration_count{instance=~\"${nodename}\"}[$__rate_interval])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Number of tasks started",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(${metric_namespace}_tasks_spawned_total{instance=~\"${nodename}\"}[$__rate_interval])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Number of tasks running",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${metric_namespace}_tasks_spawned_total{instance=~\"${nodename}\"} - sum(${metric_namespace}_tasks_ended_total{instance=~\"${nodename}\"}) without(reason)\n\n# Fallback if tasks_ended_total is null for that task\nor on(instance, task_name) ${metric_namespace}_tasks_spawned_total{instance=~\"${nodename}\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Number of calls to `Future::poll` that took more than one second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "cps", "label": "Calls to `Future::poll`/second" }
   ],
   "targets": [
    {
     "expr": "irate(${metric_namespace}_tasks_polling_duration_bucket{instance=~\"${nodename}\", le=\"+Inf\"}[$__rate_interval])\n    - ignoring(le)\n  irate(${metric_namespace}_tasks_polling_duration_bucket{instance=~\"${nodename}\", le=\"1.024\"}[$__rate_interval]) > 0",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  { "title": "Unbounded Channels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Unbounded channels size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  ${metric_namespace}_unbounded_channel_len{instance=~\"${nodename}\", action = \"send\"} - ignoring(action) ${metric_namespace}_unbounded_channel_len{instance=~\"${nodename}\", action = \"received\"}\n)\n\n# Fallback if the `received` is null\nor on(instance) ${metric_namespace}_unbounded_channel_len{instance=~\"${nodename}\", action = \"send\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Unbounded channels message sending rate (1s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "irate(${metric_namespace}_unbounded_channel_len{instance=~\"${nodename}\", action = \"send\"}[$__rate_interval])",
     "legendFormat": "{{entity}}"
    }
   ]
  }
 ]
}