#!/bin/sh

if command -v taplo &> /dev/null; then
    taplo fmt --config ./taplo/taplo.toml --check
else
    npx @taplo/cli fmt --config ./taplo/taplo.toml --check
fi
cargo fmt --all -- --check
npx prettier --check .
cd tests
npx eslint .
