(function() {var implementors = {
"madara":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"madara/commands/run/enum.Sealing.html\" title=\"enum madara::commands::run::Sealing\">Sealing</a>"]],
"madara_runtime":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"madara_runtime/struct.Runtime.html\" title=\"struct madara_runtime::Runtime\">Runtime</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"madara_runtime/enum.RuntimeLockId.html\" title=\"enum madara_runtime::RuntimeLockId\">RuntimeLockId</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"madara_runtime/enum.RuntimeSlashReason.html\" title=\"enum madara_runtime::RuntimeSlashReason\">RuntimeSlashReason</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"madara_runtime/enum.RuntimeFreezeReason.html\" title=\"enum madara_runtime::RuntimeFreezeReason\">RuntimeFreezeReason</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"madara_runtime/enum.RuntimeHoldReason.html\" title=\"enum madara_runtime::RuntimeHoldReason\">RuntimeHoldReason</a>"]],
"mc_data_availability":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"mc_data_availability/enum.DaMode.html\" title=\"enum mc_data_availability::DaMode\">DaMode</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"mc_data_availability/enum.DaLayer.html\" title=\"enum mc_data_availability::DaLayer\">DaLayer</a>"]],
"mc_settlement":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"mc_settlement/enum.SettlementLayer.html\" title=\"enum mc_settlement::SettlementLayer\">SettlementLayer</a>"]],
"mp_block":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"mp_block/enum.BlockId.html\" title=\"enum mp_block::BlockId\">BlockId</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"mp_block/enum.BlockTag.html\" title=\"enum mp_block::BlockTag\">BlockTag</a>"]],
"mp_fee":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"mp_fee/struct.ResourcePrice.html\" title=\"struct mp_fee::ResourcePrice\">ResourcePrice</a>"]],
"mp_felt":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"mp_felt/struct.Felt252Wrapper.html\" title=\"struct mp_felt::Felt252Wrapper\">Felt252Wrapper</a>"]],
"mp_genesis_config":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"mp_genesis_config/struct.HexFelt.html\" title=\"struct mp_genesis_config::HexFelt\">HexFelt</a>"]],
"mp_hashers":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"mp_hashers/pedersen/struct.PedersenHasher.html\" title=\"struct mp_hashers::pedersen::PedersenHasher\">PedersenHasher</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"mp_hashers/poseidon/struct.PoseidonHasher.html\" title=\"struct mp_hashers::poseidon::PoseidonHasher\">PoseidonHasher</a>"]],
"mp_sequencer_address":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"mp_sequencer_address/struct.InherentDataProvider.html\" title=\"struct mp_sequencer_address::InherentDataProvider\">InherentDataProvider</a>"]],
"mp_storage":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"mp_storage/enum.StarknetStorageSchemaVersion.html\" title=\"enum mp_storage::StarknetStorageSchemaVersion\">StarknetStorageSchemaVersion</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()