[package]
name = "mp-block"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "The starknet block"
authors = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
blockifier = { workspace = true }
mp-felt = { workspace = true }
mp-hashers = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
sp-core = { workspace = true }
starknet_api = { workspace = true }

# Optionals
parity-scale-codec = { workspace = true, features = [
  "derive",
], optional = true }
scale-info = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
mp-hashers = { workspace = true }
mp-felt = { workspace = true }

[features]
parity-scale-codec = ["dep:parity-scale-codec", "mp-felt/parity-scale-codec"]
scale-info = ["dep:scale-info"]
