[package]
name = "mp-consensus"
version = "0.1.0-dev"
license = "MIT"
description = "Primitives for Madara consensus."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
mp-starknet = { path = "../starknet", default-features = false }
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false }
# Substrate
sp-core = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
	"mp-starknet/std",
	"codec/std",
	# Substrate
	"sp-core/std",
	"sp-runtime/std",
]
