// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// StakesColumns holds the columns for the "stakes" table.
	StakesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "staker", Type: field.TypeString, Size: 90},
		{Name: "tx", Type: field.TypeString, Unique: true, Size: 66},
		{Name: "start", Type: field.TypeInt64},
		{Name: "duration", Type: field.TypeInt64},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "receiver", Type: field.TypeString, Size: 66},
		{Name: "finalized", Type: field.TypeBool},
		{Name: "end", Type: field.TypeBool, Default: false},
		{Name: "btc_sig", Type: field.TypeString},
		{Name: "receiver_sig", Type: field.TypeString},
	}
	// StakesTable holds the schema information for the "stakes" table.
	StakesTable = &schema.Table{
		Name:       "stakes",
		Columns:    StakesColumns,
		PrimaryKey: []*schema.Column{StakesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "stake_staker_tx",
				Unique:  false,
				Columns: []*schema.Column{StakesColumns[1], StakesColumns[2]},
			},
			{
				Name:    "stake_end_tx",
				Unique:  false,
				Columns: []*schema.Column{StakesColumns[8], StakesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		StakesTable,
	}
)

func init() {
}
