[package]
name = "pallet-starknet-runtime-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Madara primitives
mp-felt = { workspace = true, features = ["parity-scale-codec", "serde"] }
mp-simulations = { workspace = true, features = [
  "parity-scale-codec",
  "scale-info",
] }

# Starknet
blockifier = { workspace = true }
starknet_api = { workspace = true }

# Substrate
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
sp-api = { workspace = true }
sp-runtime = { workspace = true }
