[package]
name = "snos-feeder"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snos = {git = "https://github.com/keep-starknet-strange/snos", branch = "main" }
blockifier = { workspace = true, features = ["std"] }
