[package]
name = "mp-messages"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Starknet l1-l2 messages"
authors = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
starknet_api = { workspace = true }

# Optional
parity-scale-codec = { workspace = true, features = [
  "derive",
], optional = true }
scale-info = { workspace = true, features = ["derive"], optional = true }
serde = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true }

[features]
parity-scale-codec = ["dep:parity-scale-codec"]
scale-info = ["dep:scale-info"]
serde = ["dep:serde", "dep:serde_with"]
