[package]
name = "mp-fee"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Starknet fee related logic"
authors = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
blockifier = { workspace = true }
sp-core = { workspace = true }
frame-support = { workspace = true }
