[package]
name = "mp-fee"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Starknet fee related logic"
authors = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
blockifier = { workspace = true }
hashbrown = { workspace = true }
mp-state = { workspace = true }
phf = { workspace = true }
sp-arithmetic = { workspace = true }
starknet_api = { workspace = true }

[features]
default = ["std"]
std = ["blockifier/std", "starknet_api/std", "mp-state/std"]
