[package]
name = "mp-state"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Starknet state logic"
authors = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
blockifier = { workspace = true }
mp-felt = { workspace = true, features = [
  "parity-scale-codec",
  "serde",
  "scale-info",
] }
serde = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true }
starknet_api = { workspace = true }

# Substrate dependencies
parity-scale-codec = { workspace = true, optional = true }
scale-info = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
  "mp-felt/std",
  "starknet_api/std",
  "blockifier/std",
  "serde?/std",
  "serde_with?/std",
  "parity-scale-codec?/std",
  "scale-info?/std",
]
parity-scale-codec = [
  "dep:parity-scale-codec",
  "starknet_api/parity-scale-codec",
  "mp-felt/parity-scale-codec",
]
serde = ["dep:serde", "dep:serde_with", "mp-felt/serde"]
scale-info = ["dep:scale-info", "starknet_api/scale-info"]
