[package]
name = "mp-storage"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Starknet substrate storage const and types"
authors = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Optional
lazy_static = { workspace = true }
parity-scale-codec = { workspace = true, features = [
  "derive",
], optional = true }
serde = { workspace = true, optional = true, features = ["derive"] }
sp-io = { workspace = true }

[features]
serde = ["dep:serde"]
parity-scale-codec = ["dep:parity-scale-codec"]
