---
name: Task - Build binaries and publish

on:
  workflow_dispatch:
    inputs:
      release_tag_name:
        description: "Release tag name"
        type: string
        required: true
  workflow_call:
    inputs:
      release_tag_name:
        description: "Release tag name"
        type: string
        required: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - aarch64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
        include:
          - build: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - build: x86_64-apple-darwin
            os: macos-latest
          - build: x86_64-pc-windows-gnu
            os: ubuntu-latest
          - build: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup rust toolchain
        run: |
          rustup target add ${{ matrix.build }}

      - name: Setup build deps (linux/windows)
        if:
          matrix.build == 'x86_64-unknown-linux-gnu' || matrix.build ==
          'aarch64-unknown-linux-gnu' || matrix.build == 'x86_64-pc-windows-gnu'
        run: |
          sudo apt update
          sudo apt install -y clang llvm libudev-dev protobuf-compiler

      - name: Setup build deps (aarch64-unknown-linux-gnu)
        if: matrix.build == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt update
          sudo apt install -y g++-aarch64-linux-gnu libc6-dev-arm64-cross
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          export CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
          export CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g+

      - name: Setup build deps (x86_64-apple-darwin)
        if: matrix.build == 'x86_64-apple-darwin'
        run: |
          brew install protobuf

      - name: Setup build deps (x86_64-pc-windows-gnu)
        if: matrix.build == 'x86_64-pc-windows-gnu'
        run: |
          sudo apt update
          sudo apt install -y g++-mingw-w64-x86-64

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Build
        run: cargo build --release --target ${{ matrix.build }}

      - name: Upload binaries
        if: github.event.inputs.release_tag_name
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.build }}
          path: target/${{ matrix.build }}/release

      - name: Upload source
        if: github.event.inputs.release_tag_name
        uses: actions/upload-artifact@v2
        with:
          name: source
          path: target/${{ matrix.build }}/release
