name: Workflow - Daily Cron
  
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale_issues:
    name: Stale issues
    uses: ./.github/workflows/stale-issues.yml

  lock_closed:
    name: Lock closed issues/PRs
    uses: ./.github/workflows/lock-closed.yml

  security_audit:
    name: Security audit
    uses: ./.github/workflows/security-audit.yml

  docker_nightly_build:
    name: Docker nightly build
    uses: ./.github/workflow/tasks/docker-build.yml
