---
name: Workflow - Daily Cron

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  weekly_pre_release:
    name: Weekly pre-release
    uses: ./.github/workflows/docker-build.yml
    with:
      release_tag_name: nightly-${{ dateFormat(now(), 'YYYY-MM-DD') }}
