name: Build and Push Docker Image

on:
  release:
    types:
      - created

jobs:
  build-amd64-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          file: infra/docker/Dockerfile
          tags: >
            ghcr.io/${{ github.repository }}:latest,
            ghcr.io/${{github.repository }}:${{ github.event.release.tag_name }}

  build-arm64-and-push:
    runs-on: ubuntu-latest-32-cores

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          push: true
          file: infra/docker/Dockerfile
          tags: >
            ghcr.io/${{ github.repository }}:latest,
            ghcr.io/${{github.repository }}:${{ github.event.release.tag_name }}
