---
name: Task - Pre-Release

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Take Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Get the tags by date
        id: tags
        run: |
          echo "new=$(date +'weekly-%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "old=$(date -d'1 week ago' +'weekly-%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Checkout branch "main"
        uses: actions/checkout@v3
        with:
          ref: "main"
          fetch-depth: 0
      - name: Generate changelog
        id: changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# Automatic snapshot pre-release ${{ steps.tags.outputs.new }}" > Changelog.md
          echo "" >> Changelog.md
          echo "## Changes since last snapshot (${{ steps.tags.outputs.old }})" >> Changelog.md
          echo "" >> Changelog.md
      - name: Release snapshot
        id: release-snapshot
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4 latest version, repo archived
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tags.outputs.new }}
          release_name: ${{ steps.tags.outputs.new }}
          draft: false
          prerelease: true
          body_path: Changelog.md
