name: Spell Check

on: [push, pull_request]

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@v1
        with:
          check_filenames: true
          check_hidden: true
          ignore_words_file: ./.codespellignore
          skip: Cargo.lock,package-lock.json,target,yarn.lock,.git,resources
